# fly.toml app configuration file generated for easy-manage-api on 2023-08-24T18:31:01+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "easy-manage-api"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
